

client:
	python3 client/main.py ftp.georgetown.page ftpuser hostilespacesound --use_plain
.PHONY: client

proxy:
	python3 proxy/main.py ftp.georgetown.page ftpuser hostilespacesound --use_plain
.PHONY: proxy
